# Generated by Django 5.2.7 on 2025-10-29 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviesource_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='movietag',
            options={'verbose_name': 'Тег фильма', 'verbose_name_plural': 'Теги фильмов'},
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieActor', to='movies.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieDirector', to='movies.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieTag', to='movies.tag'),
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_movies', to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Жанр фильма',
                'verbose_name_plural': 'Жанры фильмов',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieGenre', to='movies.genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year', 'rating'], name='movies_movi_year_e9ced8_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['approved', 'year'], name='movies_movi_approve_59ed36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviegenre',
            unique_together={('movie', 'genre')},
        ),
    ]
