# Generated by Django 5.2.7 on 2025-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_alter_movie_options_alter_movietag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, help_text='Продолжительность фильма в формате ЧЧ:ММ:СС', null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
    ]
