# Generated by Django 5.2.8 on 2025-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_alter_movie_options_alter_movietag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True, help_text='Продолжительность фильма в формате ЧЧ:ММ:СС', null=True, verbose_name='Продолжительность'),
        ),
    ]
